insert into team VALUES(1, 'CHI', 'Chicago', 'East', 'Central', 'Chicago', 'Chicago Zephyr''s', 'Zephyrs', 'Chicago Coliseum', 'IL', 'chicago-zephyr''s');
insert into team VALUES(2, 'HAR', 'Harlem', 'East', 'Atlantic', 'Harlem', 'Harlem Globetrotter''s', 'Globetrotter''s', 'Rucker Park', 'NY', 'harlem-globetrotter''s');
insert into team VALUES(3, 'STL', 'St. Louis', 'East', 'Southwest', 'St. Louis', 'St. Louis Bomber''s', 'Bomber''s', 'St. Louis Arena', 'MO', 'st-louis-bomber''s');
insert into team VALUES(4, 'SAL', 'Salinas', 'West', 'Pacific', 'Salinas', 'Salinas Cowboys', 'Cowboys', 'Salinas High School', 'CA', 'salinas-cowboys');
-- insert into team VALUES(5, 'STL', 'Baltimore', 'East', 'Southeast', 'Baltimore', 'Baltimore Bullets', 'Bullets', 'Baltimore Coliseum', 'MD', 'baltimore-bullets');
insert into team VALUES(6, 'CLE', 'Rebels', 'East', 'Central', 'Cleveland', 'Cleveland Rebels', 'Rebels', 'Cleveland Arena', 'OH', 'cleveland-rebels');
insert into team VALUES(7, 'ROC', 'Rochester', 'East', 'Atlantic', 'Rochester', 'Rochester Royals', 'Royals', 'Edgerton Park Arena', 'NY', 'rochester-royals');
-- insert into team VALUES(8, 'STL', 'St. Louis', 'East', 'Southwest', 'St. Louis', 'St. Louis Bomber''s', 'Bomber''s', 'St. Louis Multiplex', 'MO', 'st-louis-bomber''s');
insert into team VALUES(9, 'DET', 'Detroit', 'East', 'Central', 'Detroit', 'Detroit Pistons', 'Pistons', 'Palace of Auburn Hills', 'MI', 'detroit-pistons');
insert into team VALUES(20, 'CHI', 'Chicago', 'East', 'Central', 'Chicago', 'Chicago Bulls', 'Bulls', 'United Center', 'IL', 'chicago-bulls');
insert into team VALUES(21, 'UTA', 'Salt Lake City', 'West', 'Northwest', 'Utah', 'Utah Jazz', 'Jazz', 'Energy Solutions Arena', 'UT', 'utah-jazz');
